title: Mockrobiota
description: A public resource for microbiome bioinformatics benchmarking using artificially constructed (i.e., mock) communities.
google_analytics: 
show_downloads: true
theme: jekyll-theme-tactile

gems:
  - jekyll-mentions
